# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(default='Employee name', max_length=200)),
                ('emp_title', models.CharField(default='Title', max_length=100)),
                ('emp_bio', models.TextField(default='I love the agency')),
                ('emp_photo', models.ImageField(blank=True, upload_to='Emp Photo')),
            ],
        ),
    ]
