# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetails',
            name='emp_photo',
        ),
    ]
