# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employeedetails_emp_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='emp_image',
            field=models.ImageField(default='Img.jpg', upload_to='Images/'),
        ),
    ]
